"""session start sha

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_sha', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_column('start_sha')

    # ### end Alembic commands ###
